name: release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install --upgrade pip build

    - name: Build package
      run: python -m build .

    - name: Parse changelog for release notes
      run: python .github/workflows/parse_changelog.py CHANGELOG.md ${{ github.ref_name }} body.md

    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        bodyFile: "body.md"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
